### PR TITLE
Default modules

### PR DESCRIPTION
**Pull request by adamf321**
- **What kind of change does this PR introduce?** (Bug fix, feature,
  docs update, ...)
  Feture
- **What is the current behavior?** (You can also link to an open issue
  here)
  Missing some default modules
- **What is the new behavior (if this is a feature change)?**
  Add default modules
- **Does this PR introduce a breaking change?** (What changes might
  users need to make in their application due to this PR?)
  No
- **Other information**:

### CODE REVIEW

**Comment by mitogh** [comment]
I think we should start by getting ride of the `Inc` dir

**Comment by adamf321** [comment]
Do you propose we move them all up a level, eg \Leean\Menus ?

**Comment by mitogh** [comment]
I think we have to put them inside of a namespace that makes more sense rather than `Inc` something like `Menus` as you mentioned or `UI\Menus`  or something similar makes more sense than `Inc`

**Comment by adamf321** [comment]
Let's just move them up a level for now

**Pull request merged**
